<a href="https://colab.research.google.com/github/SanjaraT/PyTorch-from-beginning/blob/main/pytorch_dataset_dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import make_classification
import torch

In [17]:
# Dateset using sklearn
X, y = make_classification(
    n_samples=100,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [18]:
# Converting data to pytorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [19]:
X

tensor([[ 0.5594,  2.3887],
        [ 1.3122, -0.7173],
        [-1.5598, -1.9249],
        [-2.2814, -0.1369],
        [ 1.5607, -0.4280],
        [-0.8080,  1.1966],
        [-0.2706, -2.2555],
        [ 0.4805,  0.5491],
        [-1.2076, -1.2690],
        [ 0.2542, -1.7953],
        [ 2.5912,  0.2447],
        [ 0.0712,  0.4943],
        [-1.1776, -1.2059],
        [ 0.9334,  0.6881],
        [ 1.6521, -0.3589],
        [-1.4074, -1.5683],
        [ 1.0226, -1.0832],
        [-0.8168, -0.6796],
        [ 1.5058, -0.3892],
        [-2.1711, -0.0486],
        [ 0.7148, -1.4292],
        [-0.1501, -0.1171],
        [-1.4118, -1.5333],
        [-2.5859, -0.4093],
        [ 0.8260, -1.0538],
        [-0.0713,  0.0890],
        [ 0.6274, -1.3293],
        [ 1.6588, -0.4313],
        [ 1.2799,  1.2590],
        [ 0.2506,  0.1398],
        [-0.0532,  1.8561],
        [-2.0583, -2.5234],
        [-2.0263,  0.0619],
        [-1.6583, -1.5713],
        [ 1.2801,  1.2894],
        [ 0.9642,  0

In [20]:
X.shape[1]

2

In [21]:
from torch.utils.data import Dataset, DataLoader

In [22]:
# Dataset Class
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels
  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [23]:
# object of custom dataset
dataset = CustomDataset(X, y)

In [24]:
len(dataset)

100

In [25]:
# dataloader object
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [26]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 1.8638,  1.5949],
        [ 0.8260, -1.0538]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 0.0685, -1.7360],
        [ 0.2506,  0.1398]])
tensor([1, 1])
--------------------------------------------------
tensor([[-0.0532,  1.8561],
        [-1.6930, -1.6145]])
tensor([0, 0])
--------------------------------------------------
tensor([[-0.5677,  1.3899],
        [-0.3314,  1.5693]])
tensor([0, 0])
--------------------------------------------------
tensor([[ 1.2799,  1.2590],
        [-1.0983, -0.8602]])
tensor([1, 0])
--------------------------------------------------
tensor([[-0.3857,  0.0172],
        [ 0.9642,  0.5560]])
tensor([0, 1])
--------------------------------------------------
tensor([[-1.1321,  0.8908],
        [ 0.2542, -1.7953]])
tensor([0, 1])
--------------------------------------------------
tensor([[0.3413, 0.5730],
        [2.5912, 0.2447]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.4683, -0