<a href="https://colab.research.google.com/github/SanjaraT/PyTorch-from-beginning/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


#Creating Tensor

In [ ]:
a = torch.empty(2,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,2)

tensor([[0.8859, 0.6829],
        [0.5319, 0.5588]])

In [ ]:
torch.rand(2,2)

tensor([[0.1872, 0.7993],
        [0.8357, 0.7750]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [ ]:
torch.tensor([[1,2,5],[3,4,6]])

tensor([[1, 2, 5],
        [3, 4, 6]])

In [ ]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [ ]:
torch.arange(0,10,3)

tensor([0, 3, 6, 9])

In [ ]:
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.full((4,4),5)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

#Tensor Shape

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x.shape

torch.Size([3, 3])

In [ ]:
print("Same shape : ",torch.empty_like(x))
print("Same shape with zeros : ",torch.zeros_like(x))
print("Same shape with ones : ",torch.ones_like(x))

Same shape :  tensor([[      234570880, 138814151791296,               0],
        [              0,               0,               0],
        [              0,               0,               1]])
Same shape with zeros :  tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
Same shape with ones :  tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


#Tensor Data types


In [ ]:
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0, 2.2, 3.5], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1, 2, 3], dtype=torch.float32)

tensor([1., 2., 3.])

In [ ]:
# change data type
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

#Mathematical Operations

In [ ]:
y = torch.rand(3,3)
y

tensor([[0.6765, 0.7539, 0.2627],
        [0.0428, 0.2080, 0.1180],
        [0.1217, 0.7356, 0.7118]])

In [ ]:
print("Add: ", y + 2)
print("Sub: ", y - 2)
print("Mul: ", y * 2)
print("Div: ", y / 2)
print("Int Div: ", (y*100)//2)
print("Mod: ", ((y*100)//2)%2)
print("Power: ", y**2)

Add:  tensor([[2.6765, 2.7539, 2.2627],
        [2.0428, 2.2080, 2.1180],
        [2.1217, 2.7356, 2.7118]])
Sub:  tensor([[-1.3235, -1.2461, -1.7373],
        [-1.9572, -1.7920, -1.8820],
        [-1.8783, -1.2644, -1.2882]])
Mul:  tensor([[1.3530, 1.5078, 0.5254],
        [0.0857, 0.4161, 0.2361],
        [0.2434, 1.4712, 1.4235]])
Div:  tensor([[0.3383, 0.3770, 0.1313],
        [0.0214, 0.1040, 0.0590],
        [0.0608, 0.3678, 0.3559]])
Int Div:  tensor([[33., 37., 13.],
        [ 2., 10.,  5.],
        [ 6., 36., 35.]])
Mod:  tensor([[1., 1., 1.],
        [0., 0., 1.],
        [0., 0., 1.]])
Power:  tensor([[0.4577, 0.5684, 0.0690],
        [0.0018, 0.0433, 0.0139],
        [0.0148, 0.5411, 0.5066]])


In [ ]:
# Element wise
a = torch.rand(2,3)
b = torch.rand(2,3)

print("Add: ", a + b)
print("Sub: ", a - b)
print("Mul: ", a * b)
print("Div: ", a / b)
print("Mod: ", a % b)
print("Power", a**b)

Add:  tensor([[1.0899, 0.5967, 1.7253],
        [1.5526, 1.7335, 0.6679]])
Sub:  tensor([[ 0.4852,  0.2399,  0.0776],
        [ 0.4411, -0.2205, -0.2201]])
Mul:  tensor([[0.2381, 0.0746, 0.7426],
        [0.5540, 0.7391, 0.0994]])
Div:  tensor([[2.6049, 2.3445, 1.0942],
        [1.7938, 0.7743, 0.5042]])
Mod:  tensor([[0.1829, 0.0615, 0.0776],
        [0.4411, 0.7565, 0.2239]])
Power tensor([[0.9303, 0.8560, 0.9180],
        [0.9983, 0.7614, 0.5145]])


In [ ]:
# Specific Range
torch.clamp(y, min = 0.5, max = 1)

tensor([[0.6765, 0.7539, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.7356, 0.7118]])

#Reduction Operations

In [ ]:
e = torch.randint(size=(2,3), low =0, high = 10, dtype=torch.float32)
e

tensor([[1., 9., 9.],
        [8., 0., 7.]])

In [ ]:
print("Total: ", torch.sum(e))
print("Column Total: ", torch.sum(e, dim= 0))
print("Row Total: ", torch.sum(e, dim= 1))
print("Mean: ", torch.mean(e))
print("Mean of Columns: ", torch.mean(e, dim =0))
print("Median: ", torch.median(e))
print("Max: ", torch.max(e))
print("Min: ", torch.min(e))
print("Product: ", torch.prod(e))
print("Standard Deviation: ", torch.std(e))
print("Variance: ", torch.var(e))




Total:  tensor(34.)
Column Total:  tensor([ 9.,  9., 16.])
Row Total:  tensor([19., 15.])
Mean:  tensor(5.6667)
Mean of Columns:  tensor([4.5000, 4.5000, 8.0000])
Median:  tensor(7.)
Max:  tensor(9.)
Min:  tensor(0.)
Product:  tensor(0.)
Standard Deviation:  tensor(4.0825)
Variance:  tensor(16.6667)


# Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
torch.rand((2,3), device=device)

tensor([[0.9732, 0.1392, 0.9184],
        [0.8225, 0.6571, 0.9374]], device='cuda:0')

In [ ]:
#moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.5345, 0.1096, 0.4021],
        [0.4432, 0.4616, 0.3688]])

In [ ]:
b= a.to(device)
b

tensor([[0.5345, 0.1096, 0.4021],
        [0.4432, 0.4616, 0.3688]], device='cuda:0')

# Reshaping Tenosrs

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# Permute
b = torch.rand(2,3,4)
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [ ]:
#Unsqueeze/Squeeze
c= torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# Numpy and PyTorch

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()
b

array([1, 2, 3])

In [ ]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)


tensor([1, 2, 3])

# PyTorch Autograd

y = x^2 // dy/dx

In [2]:
x = torch.tensor(3.0, requires_grad=True)


In [3]:
y = x**2

In [4]:
y.backward()

In [5]:
x.grad

tensor(6.)

dz/dy | dy/dx

In [6]:
x = torch.tensor(3.0, requires_grad=True)

In [19]:
x

tensor(3., requires_grad=True)

In [20]:
y = x**2

In [21]:
z = torch.sin(y)

In [22]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [23]:
x.grad

single NN

In [24]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [26]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [27]:
w

tensor(1., requires_grad=True)

In [28]:
b

tensor(0., requires_grad=True)

In [29]:
z = w*x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [30]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [32]:
import torch.nn.functional as F

loss = F.binary_cross_entropy(y_pred, y)
loss

tensor(6.7012, grad_fn=<BinaryCrossEntropyBackward0>)

In [33]:
loss.backward()

In [34]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)
