<a href="https://colab.research.google.com/github/SanjaraT/PyTorch-from-beginning/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.9.0+cu128


#Creating Tensor

In [4]:
a = torch.empty(2,3)

In [5]:
type(a)

torch.Tensor

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,2)

tensor([[0.3439, 0.3457],
        [0.4080, 0.2682]])

In [10]:
torch.rand(2,2)

tensor([[0.6765, 0.7539],
        [0.2627, 0.0428]])

In [11]:
torch.manual_seed(100)
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [12]:
torch.manual_seed(100)
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [15]:
torch.tensor([[1,2,5],[3,4,6]])

tensor([[1, 2, 5],
        [3, 4, 6]])

In [17]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [18]:
torch.arange(0,10,3)

tensor([0, 3, 6, 9])

In [20]:
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [21]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
torch.full((4,4),5)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])