<a href="https://colab.research.google.com/github/SanjaraT/PyTorch-from-beginning/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.9.0+cu128


#Creating Tensor

In [3]:
a = torch.empty(2,3)

In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,2)

tensor([[0.8859, 0.6829],
        [0.5319, 0.5588]])

In [8]:
torch.rand(2,2)

tensor([[0.1872, 0.7993],
        [0.8357, 0.7750]])

In [9]:
torch.manual_seed(100)
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [10]:
torch.manual_seed(100)
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [11]:
torch.tensor([[1,2,5],[3,4,6]])

tensor([[1, 2, 5],
        [3, 4, 6]])

In [12]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [13]:
torch.arange(0,10,3)

tensor([0, 3, 6, 9])

In [14]:
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [15]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [16]:
torch.full((4,4),5)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

#Tensor Shape

In [17]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
x.shape

torch.Size([3, 3])

In [19]:
print("Same shape : ",torch.empty_like(x))
print("Same shape with zeros : ",torch.zeros_like(x))
print("Same shape with ones : ",torch.ones_like(x))

Same shape :  tensor([[      234570880, 138814151791296,               0],
        [              0,               0,               0],
        [              0,               0,               1]])
Same shape with zeros :  tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
Same shape with ones :  tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


#Tensor Data types


In [20]:
x.dtype

torch.int64

In [21]:
# assign data type
torch.tensor([1.0, 2.2, 3.5], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [22]:
torch.tensor([1, 2, 3], dtype=torch.float32)

tensor([1., 2., 3.])

In [24]:
# change data type
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

#Mathematical Operations

In [25]:
y = torch.rand(3,3)
y

tensor([[0.6765, 0.7539, 0.2627],
        [0.0428, 0.2080, 0.1180],
        [0.1217, 0.7356, 0.7118]])

In [26]:
print("Add: ", y + 2)
print("Sub: ", y - 2)
print("Mul: ", y * 2)
print("Div: ", y / 2)
print("Int Div: ", (y*100)//2)
print("Mod: ", ((y*100)//2)%2)
print("Power: ", y**2)

Add:  tensor([[2.6765, 2.7539, 2.2627],
        [2.0428, 2.2080, 2.1180],
        [2.1217, 2.7356, 2.7118]])
Sub:  tensor([[-1.3235, -1.2461, -1.7373],
        [-1.9572, -1.7920, -1.8820],
        [-1.8783, -1.2644, -1.2882]])
Mul:  tensor([[1.3530, 1.5078, 0.5254],
        [0.0857, 0.4161, 0.2361],
        [0.2434, 1.4712, 1.4235]])
Div:  tensor([[0.3383, 0.3770, 0.1313],
        [0.0214, 0.1040, 0.0590],
        [0.0608, 0.3678, 0.3559]])
Int Div:  tensor([[33., 37., 13.],
        [ 2., 10.,  5.],
        [ 6., 36., 35.]])
Mod:  tensor([[1., 1., 1.],
        [0., 0., 1.],
        [0., 0., 1.]])
Power:  tensor([[0.4577, 0.5684, 0.0690],
        [0.0018, 0.0433, 0.0139],
        [0.0148, 0.5411, 0.5066]])


In [27]:
# Element wise
a = torch.rand(2,3)
b = torch.rand(2,3)

print("Add: ", a + b)
print("Sub: ", a - b)
print("Mul: ", a * b)
print("Div: ", a / b)
print("Mod: ", a % b)
print("Power", a**b)

Add:  tensor([[1.0899, 0.5967, 1.7253],
        [1.5526, 1.7335, 0.6679]])
Sub:  tensor([[ 0.4852,  0.2399,  0.0776],
        [ 0.4411, -0.2205, -0.2201]])
Mul:  tensor([[0.2381, 0.0746, 0.7426],
        [0.5540, 0.7391, 0.0994]])
Div:  tensor([[2.6049, 2.3445, 1.0942],
        [1.7938, 0.7743, 0.5042]])
Mod:  tensor([[0.1829, 0.0615, 0.0776],
        [0.4411, 0.7565, 0.2239]])
Power tensor([[0.9303, 0.8560, 0.9180],
        [0.9983, 0.7614, 0.5145]])


In [30]:
# Specific Range
torch.clamp(y, min = 0.5, max = 1)

tensor([[0.6765, 0.7539, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.7356, 0.7118]])