<a href="https://colab.research.google.com/github/SanjaraT/PyTorch-from-beginning/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import torch
print(torch.__version__)

2.9.0+cu128


#Creating Tensor

In [24]:
a = torch.empty(2,3)

In [25]:
type(a)

torch.Tensor

In [26]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [27]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [28]:
torch.rand(2,2)

tensor([[0.6765, 0.7539],
        [0.2627, 0.0428]])

In [29]:
torch.rand(2,2)

tensor([[0.2080, 0.1180],
        [0.1217, 0.7356]])

In [30]:
torch.manual_seed(100)
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [31]:
torch.manual_seed(100)
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [32]:
torch.tensor([[1,2,5],[3,4,6]])

tensor([[1, 2, 5],
        [3, 4, 6]])

In [33]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [34]:
torch.arange(0,10,3)

tensor([0, 3, 6, 9])

In [35]:
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [36]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [37]:
torch.full((4,4),5)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

#Tensor Shape

In [38]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [39]:
x.shape

torch.Size([3, 3])

In [40]:
print("Same shape : ",torch.empty_like(x))
print("Same shape with zeros : ",torch.zeros_like(x))
print("Same shape with ones : ",torch.ones_like(x))

Same shape :  tensor([[              0,       972563488,       943732960],
        [132726431839760,               0,               0],
        [              0,               0,               0]])
Same shape with zeros :  tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
Same shape with ones :  tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
